# Generated by Django 2.2.9 on 2020-01-22 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='英文名称')),
                ('category', models.CharField(choices=[('遗传病', '遗传病'), ('肿瘤', '肿瘤'), ('心脑血管疾病', '心脑血管疾病'), ('呼吸系统疾病', '呼吸系统疾病'), ('消化系统疾病', '血液系统疾病'), ('代谢类疾病', '代谢类疾病'), ('免疫类疾病', '免疫类疾病'), ('泌尿系统疾病', '泌尿系统疾病'), ('生殖系统疾病', '生殖系统疾病'), ('皮肤系统疾病', '皮肤系统疾病'), ('精神心理疾病', '精神心理疾病'), ('眼耳疾病', '眼耳疾病'), ('骨骼肌肉疾病', '骨骼肌肉疾病')], max_length=50, verbose_name='分类')),
                ('introduction', models.TextField(verbose_name='疾病简介')),
                ('symptom', models.TextField(blank=True, null=True, verbose_name='临床症状')),
                ('incidence', models.FloatField(blank=True, null=True, verbose_name='发病率，每10万人')),
                ('mortality', models.FloatField(blank=True, null=True, verbose_name='死亡率，每10万人')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='地域')),
                ('population', models.CharField(blank=True, max_length=50, null=True, verbose_name='高发人群')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='好发年龄')),
                ('age_choice', models.CharField(choices=[('child', '儿童'), ('adult', '成年人'), ('old', '老年人'), ('all', '不限')], default='all', max_length=50, verbose_name='年龄分类')),
                ('gender_choice', models.CharField(choices=[('male', '男'), ('female', '女'), ('all', '不限')], default='all', max_length=50, verbose_name='性别分类')),
                ('advice_enviroment', models.TextField(blank=True, null=True, verbose_name='环境建议')),
                ('advice_food', models.TextField(blank=True, null=True, verbose_name='饮食建议')),
                ('advice_sport', models.TextField(blank=True, null=True, verbose_name='运动建议')),
                ('advice_mental', models.TextField(blank=True, null=True, verbose_name='心理建议')),
                ('advice_medical', models.TextField(blank=True, null=True, verbose_name='医学建议')),
            ],
            options={
                'verbose_name': '疾病',
                'verbose_name_plural': '疾病',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='基因名称')),
                ('alias_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='别名')),
                ('chain', models.CharField(default='+', max_length=1, verbose_name='正负链')),
                ('chromosome', models.CharField(blank=True, max_length=20, null=True, verbose_name='染色体')),
                ('start', models.PositiveIntegerField(blank=True, null=True, verbose_name='起点位置')),
                ('end', models.PositiveIntegerField(blank=True, null=True, verbose_name='终点位置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='基因介绍（英文）')),
                ('translation', models.TextField(blank=True, null=True, verbose_name='基因介绍（中文）')),
                ('ref_version', models.CharField(choices=[('hg19', 'hg19'), ('hg38', 'hg38')], default='hg19', max_length=20, verbose_name='参考基因组版本')),
            ],
            options={
                'verbose_name': 'GENE基因',
                'verbose_name_plural': 'GENE基因',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('journal', models.CharField(max_length=500, verbose_name='杂志')),
                ('year', models.PositiveSmallIntegerField(verbose_name='发表时间（年）')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('citation', models.CharField(max_length=250, verbose_name='引用')),
            ],
            options={
                'verbose_name': 'PAPER文献',
                'verbose_name_plural': 'PAPER文献',
            },
        ),
        migrations.CreateModel(
            name='Snp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_id', models.CharField(max_length=20, verbose_name='dbsnp ID')),
                ('genotype', models.CharField(max_length=2, verbose_name='基因型')),
                ('snp_name', models.CharField(default=uuid.uuid1, max_length=50, unique=True, verbose_name='合并名称')),
                ('chromosome', models.CharField(blank=True, max_length=50, null=True, verbose_name='染色体')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='位置')),
                ('ref_or_not', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否参考基因型')),
                ('han_population_freq', models.FloatField(blank=True, null=True, verbose_name='汉族人中的频率')),
                ('world_population_freq', models.FloatField(blank=True, null=True, verbose_name='人群中的频率')),
                ('dbsnp_version', models.PositiveSmallIntegerField(blank=True, default=141, null=True, verbose_name='dbsnp 版本号')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Gene', to_field='name', verbose_name='归属基因名')),
            ],
            options={
                'verbose_name': 'SNP突变',
                'verbose_name_plural': 'SNP突变',
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='英文名称')),
                ('category', models.CharField(choices=[('运动基因', '运动基因'), ('美容基因', '美容基因'), ('营养基因', '营养基因'), ('身体特征', '身体特征'), ('潜能与性格', '潜能与性格')], max_length=50, verbose_name='分类')),
                ('introduction', models.TextField(verbose_name='背景介绍')),
                ('advice_good', models.TextField(blank=True, null=True, verbose_name='良好水平建议')),
                ('advice_avg', models.TextField(blank=True, null=True, verbose_name='平均水平建议')),
                ('advice_bad', models.TextField(blank=True, null=True, verbose_name='较弱水平建议')),
                ('age_choice', models.CharField(choices=[('child', '儿童'), ('adult', '成年人'), ('old', '老年人'), ('all', '不限')], default='all', max_length=50, verbose_name='年龄相关性')),
                ('gender_choice', models.CharField(choices=[('male', '男'), ('female', '女'), ('all', '不限')], default='all', max_length=50, verbose_name='性别相关性')),
            ],
            options={
                'verbose_name': '性状',
                'verbose_name_plural': '性状',
            },
        ),
        migrations.CreateModel(
            name='TraitSnp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.FloatField(blank=True, null=True, verbose_name='突变贡献度')),
                ('paper', models.ManyToManyField(to='data.Paper', verbose_name='文献')),
                ('snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Snp', to_field='snp_name', verbose_name='突变-外键')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Trait', to_field='name', verbose_name='性状-外键')),
            ],
            options={
                'verbose_name': '性状-突变-关联',
                'verbose_name_plural': '性状-突变-关联',
            },
        ),
        migrations.CreateModel(
            name='DiseaseSnp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_value', models.FloatField(blank=True, null=True, verbose_name='突变OR值')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Disease', to_field='name', verbose_name='疾病-外键')),
                ('paper', models.ManyToManyField(to='data.Paper', verbose_name='文献')),
                ('snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Snp', to_field='snp_name', verbose_name='突变-外键')),
            ],
            options={
                'verbose_name': '疾病-突变-关联',
                'verbose_name_plural': '疾病-突变-关联',
            },
        ),
    ]
